#!/bin/bash

A=(4 3 0 0 4 2 -1)
B=(9 4 2 8 2 1 2)
C=(3 6 3 4 7 1 5)
D=(2 3 2 2 5 1 3)
E=(1 1 6 1 2 1 5)
F=(1 1 1 1 1 4 1)
G=(4 4 3 1 4 0 2)

MAINresults=(1 1 0 0 0 1 0)
NEGresults=(0 0 1 1 1 0 1)

echo "MAIN"
g++ -o main main.cpp

for i in `seq 0 6`; do
x=`./main ${A[$i]} ${B[$i]} ${C[$i]} ${D[$i]} ${E[$i]} ${F[$i]} ${G[$i]}`
# echo $x
# echo ${MAINresults[$i]}
if [  $x == ${MAINresults[$i]} ] ; then
echo "OK"
fi
if [  $x != ${MAINresults[$i]} ] ; then
echo "input"  ${A[$i]} ${B[$i]} ${C[$i]} ${D[$i]} ${E[$i]} ${F[$i]} ${G[$i]}
echo "output" $x
echo "expected output" ${MAINresults[$i]}
fi
done

echo "NEGACJA"
g++ -o negated negated.cpp

for i in `seq 0 6`; do
x=`./negated ${A[$i]} ${B[$i]} ${C[$i]} ${D[$i]} ${E[$i]} ${F[$i]} ${G[$i]}`
# echo $x
#echo ${NEGresults[$i]}
if [  $x == ${NEGresults[$i]} ] ; then
echo "OK"
fi
if [  $x != ${NEGresults[$i]} ] ; then
echo "input"  ${A[$i]} ${B[$i]} ${C[$i]} ${D[$i]} ${E[$i]} ${F[$i]} ${G[$i]}
echo "output" $x
echo "expected output" ${NEGresults[$i]}
fi
done
